[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "FSDecrypt"
dynamic = ["version"]
description = "Python library for reading and decrypting SEGA fscrypt containers"
readme = "README.md"
requires-python = ">=3.10"
license = "0BSD"
authors = [{ name = "beerpsi and contributors" }]
dependencies = [
    "dissect.ntfs>=3.16,<4",
    "pycryptodome>=3.20",
]

[project.urls]
Upstream = "https://gitea.tendokyu.moe/beerpsi/fsdecrypt"

[tool.setuptools.dynamic]
version = { attr = "FSDecrypt.__version__" }

[tool.setuptools.packages.find]
include = ["FSDecrypt*"]
